export const WeatherIcons: {[key:string]: string} = {
    "d000": "./assets/weather-icons/clear-day.svg",
    "d100": "./assets/weather-icons/partly-cloudy-day.svg",
    "d200": "./assets/weather-icons/partly-cloudy-day.svg",
    "d300": "./assets/weather-icons/partly-cloudy-day.svg",
    "d400": "./assets/weather-icons/cloudy.svg",
    "d500": "./assets/weather-icons/fog-day.svg",
    "d600": "./assets/weather-icons/fog.svg",
    "d210": "./assets/weather-icons/partly-cloudy-day-rain.svg",
    "d310": "./assets/weather-icons/partly-cloudy-day-rain.svg",
    "d410": "./assets/weather-icons/drizzle.svg",
    "d220": "./assets/weather-icons/partly-cloudy-day-rain.svg",
    "d320": "./assets/weather-icons/partly-cloudy-day-rain.svg",
    "d420": "./assets/weather-icons/rain.svg",
    "d430": "./assets/weather-icons/rain.svg",
    "d240": "./assets/weather-icons/thunderstorms-day-rain.svg",
    "d340": "./assets/weather-icons/thunderstorms-day-overcast-rain.svg",
    "d440": "./assets/weather-icons/thunderstorms-overcast-rain.svg",
    "d211": "./assets/weather-icons/partly-cloudy-day-sleet.svg",
    "d311": "./assets/weather-icons/partly-cloudy-day-sleet.svg",
    "d411": "./assets/weather-icons/sleet.svg",
    "d221": "./assets/weather-icons/overcast-day-sleet.svg",
    "d321": "./assets/weather-icons/overcast-day-sleet.svg",
    "d421": "./assets/weather-icons/overcast-sleet.svg",
    "d431": "./assets/weather-icons/extreme-sleet.svg",

    "d212": "./assets/weather-icons/partly-cloudy-day-snow.svg",
    "d312": "./assets/weather-icons/partly-cloudy-day-snow.svg",
    "d412": "./assets/weather-icons/snow.svg",

    "d222": "./assets/weather-icons/overcast-day-snow.svg",
    "d322": "./assets/weather-icons/overcast-day-snow.svg",
    "d422": "./assets/weather-icons/overcast-snow.svg",

    "d432": "./assets/weather-icons/extreme-snow.svg",

    "n000": "./assets/weather-icons/clear-night.svg",
    "n100": "./assets/weather-icons/partly-cloudy-night.svg",
    "n200": "./assets/weather-icons/partly-cloudy-night.svg",
    "n300": "./assets/weather-icons/partly-cloudy-night.svg",
    "n400": "./assets/weather-icons/cloudy.svg",
    "n500": "./assets/weather-icons/fog-night.svg",
    "n600": "./assets/weather-icons/fog.svg",
    "n210": "./assets/weather-icons/partly-cloudy-night-rain.svg",
    "n310": "./assets/weather-icons/partly-cloudy-night-rain.svg",
    "n410": "./assets/weather-icons/drizzle.svg",
    "n220": "./assets/weather-icons/partly-cloudy-night-rain.svg",
    "n320": "./assets/weather-icons/partly-cloudy-night-rain.svg",
    "n420": "./assets/weather-icons/rain.svg",
    "n430": "./assets/weather-icons/rain.svg",
    "n240": "./assets/weather-icons/thunderstorms-night-rain.svg",
    "n340": "./assets/weather-icons/thunderstorms-night-overcast-rain.svg",
    "n440": "./assets/weather-icons/thunderstorms-overcast-rain.svg",
    "n211": "./assets/weather-icons/partly-cloudy-night-sleet.svg",
    "n311": "./assets/weather-icons/partly-cloudy-night-sleet.svg",
    "n411": "./assets/weather-icons/sleet.svg",
    "n221": "./assets/weather-icons/overcast-night-sleet.svg",
    "n321": "./assets/weather-icons/overcast-night-sleet.svg",
    "n421": "./assets/weather-icons/overcast-sleet.svg",
    "n431": "./assets/weather-icons/extreme-sleet.svg",

    "n212": "./assets/weather-icons/partly-cloudy-night-snow.svg",
    "n312": "./assets/weather-icons/partly-cloudy-night-snow.svg",
    "n412": "./assets/weather-icons/snow.svg",

    "n222": "./assets/weather-icons/overcast-night-snow.svg",
    "n322": "./assets/weather-icons/overcast-night-snow.svg",
    "n422": "./assets/weather-icons/overcast-snow.svg",

    "n432": "./assets/weather-icons/extreme-snow.svg",
}